/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package slr1;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Arrays;
import lr0_slr1.LR0Parser;
import utilities.Rule;

/**
 *
 * @author Usama Sarwar <UsamaSarwarOfficial@gmail.com>
 * @version v1.0.0
 * @since 2020
 *
 */
public class OutputWindow extends javax.swing.JFrame {

    public LR0Parser lr0Parser;

    /**
     * Creates new form OutputWindow
     *
     * @param parserKind
     * @param lr0Parser
     * @param lR1Parser
     */
    public OutputWindow(String parserKind, LR0Parser lr0Parser) {
        this.parserKind = parserKind;
        this.lr0Parser = lr0Parser;
        initComponents();

//        result.setVisible(false);
        /*        if (parserKind.equals("LR(0)") || parserKind.equals("SLR(1)")) {
            output.setText(GrammarInputController.lr0Parser.getGrammar() + "");
        } else {
            output.setText(GrammarInputController.lr1Parser.getGrammar() + "");
        }
         */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        augmented_grammar_panel = new javax.swing.JPanel();
        result_scroll_panel = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();
        first_panel = new javax.swing.JPanel();
        result_scroll_panel1 = new javax.swing.JScrollPane();
        output1 = new javax.swing.JTextArea();
        follow_set_panel = new javax.swing.JPanel();
        result_scroll_panel2 = new javax.swing.JScrollPane();
        output2 = new javax.swing.JTextArea();
        cannonical_panel = new javax.swing.JPanel();
        result_scroll_panel3 = new javax.swing.JScrollPane();
        output3 = new javax.swing.JTextArea();
        goto_panel = new javax.swing.JPanel();
        result_scroll_panel4 = new javax.swing.JScrollPane();
        output4 = new javax.swing.JTextArea();
        action_table_panel = new javax.swing.JPanel();
        result_scroll_panel5 = new javax.swing.JScrollPane();
        output5 = new javax.swing.JTextArea();
        input_box = new javax.swing.JTextField();
        result = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.white);

        jTabbedPane1.setBackground(java.awt.Color.white);
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(56, 56, 56)));
        jTabbedPane1.setForeground(new java.awt.Color(24, 243, 179));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jTabbedPane1.setOpaque(true);
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        result_scroll_panel.setBackground(java.awt.Color.white);

        output.setColumns(20);
        output.setRows(5);
        output.setText("\n");
        result_scroll_panel.setViewportView(output);

        javax.swing.GroupLayout augmented_grammar_panelLayout = new javax.swing.GroupLayout(augmented_grammar_panel);
        augmented_grammar_panel.setLayout(augmented_grammar_panelLayout);
        augmented_grammar_panelLayout.setHorizontalGroup(
            augmented_grammar_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(augmented_grammar_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(result_scroll_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addContainerGap())
        );
        augmented_grammar_panelLayout.setVerticalGroup(
            augmented_grammar_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, augmented_grammar_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(result_scroll_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Augmented Grammar", augmented_grammar_panel);

        result_scroll_panel1.setBackground(java.awt.Color.white);

        output1.setColumns(20);
        output1.setRows(5);
        result_scroll_panel1.setViewportView(output1);

        javax.swing.GroupLayout first_panelLayout = new javax.swing.GroupLayout(first_panel);
        first_panel.setLayout(first_panelLayout);
        first_panelLayout.setHorizontalGroup(
            first_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(first_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(result_scroll_panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addContainerGap())
        );
        first_panelLayout.setVerticalGroup(
            first_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(first_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(result_scroll_panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("First Set", first_panel);

        result_scroll_panel2.setBackground(java.awt.Color.white);

        output2.setEditable(false);
        output2.setColumns(20);
        output2.setRows(5);
        result_scroll_panel2.setViewportView(output2);

        javax.swing.GroupLayout follow_set_panelLayout = new javax.swing.GroupLayout(follow_set_panel);
        follow_set_panel.setLayout(follow_set_panelLayout);
        follow_set_panelLayout.setHorizontalGroup(
            follow_set_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(follow_set_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(result_scroll_panel2, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addContainerGap())
        );
        follow_set_panelLayout.setVerticalGroup(
            follow_set_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, follow_set_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(result_scroll_panel2, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Follow Set", follow_set_panel);

        result_scroll_panel3.setBackground(java.awt.Color.white);

        output3.setEditable(false);
        output3.setColumns(20);
        output3.setRows(5);
        result_scroll_panel3.setViewportView(output3);

        javax.swing.GroupLayout cannonical_panelLayout = new javax.swing.GroupLayout(cannonical_panel);
        cannonical_panel.setLayout(cannonical_panelLayout);
        cannonical_panelLayout.setHorizontalGroup(
            cannonical_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cannonical_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(result_scroll_panel3, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addContainerGap())
        );
        cannonical_panelLayout.setVerticalGroup(
            cannonical_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cannonical_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(result_scroll_panel3, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cannonical Collection", cannonical_panel);

        result_scroll_panel4.setBackground(java.awt.Color.white);

        output4.setEditable(false);
        output4.setColumns(20);
        output4.setRows(5);
        result_scroll_panel4.setViewportView(output4);

        javax.swing.GroupLayout goto_panelLayout = new javax.swing.GroupLayout(goto_panel);
        goto_panel.setLayout(goto_panelLayout);
        goto_panelLayout.setHorizontalGroup(
            goto_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(goto_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(result_scroll_panel4, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addContainerGap())
        );
        goto_panelLayout.setVerticalGroup(
            goto_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, goto_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(result_scroll_panel4, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Goto Table", goto_panel);

        result_scroll_panel5.setBackground(java.awt.Color.white);

        output5.setEditable(false);
        output5.setColumns(20);
        output5.setRows(5);
        result_scroll_panel5.setViewportView(output5);

        javax.swing.GroupLayout action_table_panelLayout = new javax.swing.GroupLayout(action_table_panel);
        action_table_panel.setLayout(action_table_panelLayout);
        action_table_panelLayout.setHorizontalGroup(
            action_table_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(action_table_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(result_scroll_panel5, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addContainerGap())
        );
        action_table_panelLayout.setVerticalGroup(
            action_table_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, action_table_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(result_scroll_panel5, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Action Table", action_table_panel);

        input_box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                input_boxKeyReleased(evt);
            }
        });

        result.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(input_box, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(result)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(result))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        output1.setText("");
        output2.setText("");
        output3.setText("");
        output4.setText("");
        output5.setText("");

        switch (jTabbedPane1.getSelectedIndex()) {

            case 0:

                String augmentedGrammar = "";
                for (Rule s : lr0Parser.getGrammar().getRules()) {
                    augmentedGrammar += s + "\n";
                }

                output.setText(augmentedGrammar);
                augmented_grammar_panel.add(result_scroll_panel);
                break;

            case 1:
                String first = "";
                for (String s : lr0Parser.getGrammar().getFirstSets().keySet()) {
                    first += s + " : " + lr0Parser.getGrammar().getFirstSets().get(s) + "\n";
                }
                output1.append(first);
                first_panel.add(result_scroll_panel1);
                break;
            case 2:
                String follow = "";
                for (String s : lr0Parser.getGrammar().getFallowSets().keySet()) {
                    follow += s + " : " + lr0Parser.getGrammar().getFallowSets().get(s) + "\n";
                }
                output2.setText(follow);
                follow_set_panel.add(result_scroll_panel);
                break;
            case 3:
                output3.setText(lr0Parser.canonicalCollectionStr());
                cannonical_panel.add(result_scroll_panel);
                break;
            case 4:
                output4.setText(lr0Parser.goToTableStr());
                goto_panel.add(result_scroll_panel);
                break;
            case 5:
                output5.setText(lr0Parser.actionTableStr());
                action_table_panel.add(result_scroll_panel);
                break;

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void input_boxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_boxKeyReleased
        String str = input_box.getText();
        ArrayList<String> words = new ArrayList<>();
        String[] split = str.trim().split("\\s+");
        words.addAll(Arrays.asList(split));
        boolean accept = lr0Parser.accept(words);
        if (accept) {
            result.setText("accepted");
            result.setForeground(Color.GREEN);
            result.setVisible(true);
        } else {
            result.setText("not accepted");
            result.setForeground(Color.RED);
            result.setVisible(true);
        }

    }//GEN-LAST:event_input_boxKeyReleased
    String parserKind;

    public void showOutput() {
        this.setVisible(true);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OutputWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel action_table_panel;
    private javax.swing.JPanel augmented_grammar_panel;
    private javax.swing.JPanel cannonical_panel;
    private javax.swing.JPanel first_panel;
    private javax.swing.JPanel follow_set_panel;
    private javax.swing.JPanel goto_panel;
    private javax.swing.JTextField input_box;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea output;
    private javax.swing.JTextArea output1;
    private javax.swing.JTextArea output2;
    private javax.swing.JTextArea output3;
    private javax.swing.JTextArea output4;
    private javax.swing.JTextArea output5;
    private javax.swing.JLabel result;
    private javax.swing.JScrollPane result_scroll_panel;
    private javax.swing.JScrollPane result_scroll_panel1;
    private javax.swing.JScrollPane result_scroll_panel2;
    private javax.swing.JScrollPane result_scroll_panel3;
    private javax.swing.JScrollPane result_scroll_panel4;
    private javax.swing.JScrollPane result_scroll_panel5;
    // End of variables declaration//GEN-END:variables
}
